# Generated by Django 4.1.1 on 2022-09-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/%Y/%m/%d'),
        ),
    ]
