# Generated by Django 4.1.1 on 2022-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('clients_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('clients_number', models.CharField(max_length=13, verbose_name='Телефонний номер')),
                ('message', models.TextField(verbose_name='Питання')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата задання')),
                ('is_answer', models.BooleanField(default=False, verbose_name='Прочитано / Не прочитано')),
            ],
            options={
                'verbose_name': 'Запитання',
                'verbose_name_plural': 'Запитання',
                'ordering': ('date', 'is_answer', 'first_name'),
            },
        ),
    ]
