# Generated by Django 4.1.1 on 2022-09-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='clients_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
