# Generated by Django 4.1.1 on 2022-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_contacts_clients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True, null=True, verbose_name='Опубліковано'),
        ),
    ]
