# Generated by Django 4.1.1 on 2022-10-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0008_category_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('clients_number', models.CharField(max_length=13, verbose_name='Телефонний номер')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('message', models.TextField(verbose_name='Коментар до замовлення')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата задання')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершено / Не завершено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('date', 'is_finished', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Клієнт', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Товар', to='pages.product')),
            ],
        ),
    ]
